version: "3"
services:
  ftest:
    image: "ftesti"
    command:  "npx ts-node index.ts"
    restart: always
    container_name: "ft"
    logging:
      driver: "json-file"
      options:
        max-file: "6"
        max-size: "50m"
